services:
  # Backend API Service
  - type: web
    name: scratch-learning-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: scratch-learning-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: scratch-learning-frontend
          property: host

  # Frontend Web Service
  - type: web
    name: scratch-learning-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: scratch-learning-backend
          property: host

databases:
  # PostgreSQL Database
  - name: scratch-learning-db
    databaseName: scratch_learning
    region: singapore
    plan: free
